### ISSUE TITLE
Reduce docking modules mass

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/StationPartsExpansion#21]
SSPX part:

```
// Clamp-O-Tron Docking Module
@PART[crewtube-docking-125]
{
    // ~ PTD-02 / 3 + Clamp-O-Tron
    @mass = 0.15
}

// Clamp-O-Tron Sr. Docking Module
@PART[crewtube-docking-25]
{
    // ~ PPD-A2 / 3 + Clamp-O-Tron Sr.
    @mass = 0.6
}
```

What parameter is currently responsible for connection rigidness?

**Comment by ChrisAdderley** [comment]
Unfortunately, there is no such parameter.

**Comment by ChrisAdderley** [comment]
Re-evaluated in 0.4.0

**Comment by Vladimir-csp** [comment]
Was this somehow reverted? They still kinda way too heavy, 1t and 2t.
For comparison, if you mash together Clamp-O-tron, BZ-15 and empty Stratus-V, you would get 215 kilos.
