### ISSUE TITLE
Left clicks on portholes form outside of the ship switch to some strange IVA view.

### ISSUE THREAD

**Issue by WildLynxDev** [ChrisAdderley/StationPartsExpansion#26]
Left clicks from normal ship view on the porthole switches view to some strange IVA view despite module being empty.
PPD-20 Shanty and may be others.

**Comment by ChrisAdderley** [comment]
Is this still an issue in 1.2?

**Comment by WildLynxDev** [comment]
Sorry, not updated to 1.2.0/1.2.1 yet.

**Comment by WildLynxDev** [comment]
Looks fixed now.
