### ISSUE TITLE
MM patches optimization 

### ISSUE THREAD

**Issue by blackliner** [ChrisAdderley/StationPartsExpansion#38]
Your naming of the patch cfg files leads to unwanted behavior, for example a ExWorkshop is added, even if another cfg already added one (SimpleConstruction in thos case). Make a HAS[!MODULE[ExWorkshop]] or better, run patches right after you create the parts with AFTER[...]

**Comment by blackliner** [comment]
The right keywords would ofc be HAS[!MODULE[ExWorkshop]]

**Comment by ChrisAdderley** [comment]
Patches that work with mods that I don't control are community contributed and maintained. Why not submit a pull request to dev to fix this item?

**Comment by blackliner** [comment]
You mean talk to the SC guy? I think the other mod is doing nothing wrong, but its cfg file is called prior to your patch, which in turn does not check for an already existing ExWorkshop.

Oh, you mean to fix your patch file. I can try :-)

Created PR

**Comment by ChrisAdderley** [comment]
Yeah... I take these in as user-contributed patches. I don't use the other mods so I'm not very good a keeping up with them or even checking them for full compatibility. I need to rely on the community to keep them updated, which works fairly well. 

Thanks!
