### ISSUE TITLE
Some modules don't track crew experience properly

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/StationPartsExpansion#8]
Confirmed are the observation module, and the Hostel, so far.

**Comment by JZachary07** [comment]
Confirming SCATTER-1 airlock, PXL-2 conical storage container, PXL-9octo-aperture cupola, and PPD-20 shanty hab module.

**Comment by ChrisAdderley** [comment]
Looks fixed in cf41580d0b089de6e4c7878d0876f1ff91b0706d
